version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
      time: "13:00"
    open-pull-requests-limit: 10
    assignees:
      - "kawofong"
    commit-message:
      prefix: "chore(deps): "
